# Generated by Django 3.1 on 2020-10-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
